services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongo-genieacs"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb
    volumes:
      - data_db:/data/db
      - data_configdb:/data/configdb
    expose:
      - 27017
    networks:
      - genieacs_network

  genieacs:
    depends_on:
      - 'mongo'
    image: whysaputro/genieacs:v1.2.13
    restart: always
    container_name: "genieacs"
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
      - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
      - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
      - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
      - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs
      - GENIEACS_UI_INTERFACE=0.0.0.0
      - GENIEACS_FS_INTERFACE=0.0.0.0
      - GENIEACS_NBI_INTERFACE=0.0.0.0
      - GENIEACS_CWMP_INTERFACE=0.0.0.0
    ports:
      - "7547:7547"
      - "7557:7557"
      - "7567:7567"
      - "3000:3000"
    volumes:
      - opt_volume:/opt
    networks:
      - genieacs_network

volumes:
  data_db:
  data_configdb:
  opt_volume:

networks:
  genieacs_network:
